### ISSUE TITLE
Join the discussion

### ISSUE THREAD

**Issue by lakruzz** [kea-classrooms/gh-md-intro-dat22c#4]
Use your new MarkDown skill to join the discussion in the repo for this module [discussions @ kea-dev](https://github.com/orgs/kea-dev/discussions).
 
 - Consider the different categories of discussions - how are the useful? what goes where?
 - Go to the [Q&A section](ttps://github.com/kea-dev/technology-intro/discussions/categories/q-a) and see if there are any questions that needs good answers. Can you help? If some af the answers are already good - vote them up.

**Comment by MeH2607** [comment]
@lakruzz Jeg får en fejl når jeg følger linket
